Dockerfile

// command to run this thing:

// source:

// default_config
// "sinatra"
// default_config::name
// "debian_wheezy_ruby_sinatra"

# rebuild fast


FROM "sinatra"

CMD


## source

# from ""
# cmd  ""


######
